name: Create GitHub Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      environment:
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Read CHANGELOG.md
        id: changelog
        run: |
          CHANGELOG_CONTENT=$(cat CHANGELOG.md)
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get Commit Hashes
        id: hashes
        run: |
          MAIN_HASH=$(git rev-parse origin/main)
          RELEASE_HASH=${{ github.sha }}
          echo "main_hash=$MAIN_HASH" >> $GITHUB_OUTPUT
          echo "release_hash=$RELEASE_HASH" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_NOTES="## Commit Information\n"
          RELEASE_NOTES+="- Main Branch: ${{ steps.hashes.outputs.main_hash }}\n"
          RELEASE_NOTES+="- Release: ${{ steps.hashes.outputs.release_hash }}\n\n"
          RELEASE_NOTES+="## Changelog\n"
          RELEASE_NOTES+="${{ steps.changelog.outputs.content }}"
          
          gh release create "v${{ inputs.version }}" \
            --title "Release v${{ inputs.version }}" \
            --notes "$RELEASE_NOTES" \
            --hash ${{ steps.hashes.outputs.release_hash }} 