name: create-tag-on-merge

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 'Generate token'
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }} 

      - name: Create new tag
        id: tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
          RELEASE_BRANCHES: release
          PRERELEASE: true
          PRERELEASE_SUFFIX: beta

      # - name: Create Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ steps.tag.outputs.new_tag }}
      #     name: Release ${{ steps.tag.outputs.new_tag }}
      #     draft: false
      #     prerelease: true
      #     generate_release_notes: true

      - name: Merge main to release
        run: |
          git config --global user.name 'SnoopyCamp'
          git config --global user.email 'SnoopyCamp[bot]@users.noreply.github.com'
          MAIN_HASH=$(git rev-parse origin/main)
          git fetch origin release
          git checkout release
          git merge origin/main --no-ff -m "Merge main into release (main hash: ${MAIN_HASH})"
          git push origin release
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }} 