name: Create GitHub Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      environment:
        required: true
        type: string
      changelog:
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_NOTES="## Release Notes\n"
          RELEASE_NOTES+="Environment: ${{ inputs.environment }}\n\n"
          RELEASE_NOTES+="## Changelog\n"
          RELEASE_NOTES+="${{ inputs.changelog }}"
          
          # Create release with prerelease flag for UAT
          if [ "${{ inputs.environment }}" = "uat" ]; then
            gh release create "${{ inputs.version }}" \
              --title "Release ${{ inputs.version }} (UAT)" \
              --notes "$RELEASE_NOTES" \
              --prerelease
          else
            gh release create "${{ inputs.version }}" \
              --title "Release ${{ inputs.version }}" \
              --notes "$RELEASE_NOTES" 