name: generate-changelog

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  generate-changelog:
    name: generate-changelog
    if: inputs.environment == 'prod' || inputs.environment == 'uat'
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.changelog.outputs.version }}
    steps:
      - name: 'Generate token'
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: '9'

      - name: Install dependencies
        run: pnpm install

      - name: Debug - Print Branch Info
        run: |
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Git HEAD: $(git rev-parse HEAD)"
          echo "All branches:"
          git branch -a

      - name: Generate CHANGELOG
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRERELEASE: ${{ inputs.environment == 'uat' }}
        run: |
          # Enhanced debugging
          echo "=== Initial Git State ==="
          echo "GitHub SHA: ${{ github.sha }}"
          echo "GitHub REF: ${{ github.ref }}"
          echo "GitHub REF_NAME: ${{ github.ref_name }}"
          echo "Current HEAD: $(git rev-parse HEAD)"
          echo "Current Branch/Tag: $(git rev-parse --abbrev-ref HEAD)"
          git status
          
          # Store current HEAD commit hash
          CURRENT_SHA=$(git rev-parse HEAD)
          echo "Current SHA: $CURRENT_SHA"
          
          # Get the current ref (branch or tag)
          CURRENT_REF=$(git rev-parse --abbrev-ref HEAD)
          echo "Current ref: $CURRENT_REF"
          
          # If we're on a tag or detached HEAD, create branch from the commit it points to
          if [[ "$CURRENT_REF" == "HEAD" ]]; then
            echo "Detected detached HEAD state, creating branch from current commit"
            git checkout -b temp-working-branch $CURRENT_SHA
          fi
          
          # Create and push temporary branch from current HEAD
          TEMP_BRANCH="temp-release-branch-${{ github.sha }}"
          echo "Creating temporary branch: $TEMP_BRANCH"
          git checkout -b $TEMP_BRANCH
          
          echo "=== Before Push State ==="
          git status
          git branch -a
          
          # Force push to ensure the branch is created
          git push -f origin $TEMP_BRANCH
          
          echo "=== After Push State ==="
          git branch -a
          git status
          
          # Verify the branch is at the correct commit
          if [ "$(git rev-parse HEAD)" != "$CURRENT_SHA" ]; then
            echo "Error: Branch is not at the expected commit"
            echo "Expected: $CURRENT_SHA"
            echo "Got: $(git rev-parse HEAD)"
            exit 1
          fi
          
          echo "=== Running semantic-release ==="
          if [ "$PRERELEASE" = "true" ]; then
            echo "Running in prerelease mode"
            pnpm semantic-release --debug --prerelease --branches $TEMP_BRANCH > release.log 2>&1
          else
            echo "Running in release mode"
            pnpm semantic-release --debug --branches $TEMP_BRANCH > release.log 2>&1
          fi

          echo "=== semantic-release output ==="
          cat release.log
          
          # Get the version that was just released
          LATEST_VERSION=$(grep "Published release" release.log | sed -E 's/.*Published release ([0-9]+\.[0-9]+\.[0-9]+).*$/\1/' || echo "")
          echo "Released version: $LATEST_VERSION"
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          
          # If semantic-release made changes, copy them to main
          if git diff --quiet; then
            echo "No changes made by semantic-release"
          else
            echo "=== Applying Changes to Main ==="
            # Configure git user for merge commit
            git config --global user.email "SnoopyCamp[bot]@users.noreply.github.com"
            git config --global user.name "SnoopyCamp"
            
            # Get the changes from temporary branch
            git checkout main
            RELEASE_TYPE=$([ "$PRERELEASE" = "true" ] && echo "UAT" || echo "production")
            
            git merge --no-ff $TEMP_BRANCH -m "chore(release): merge ${RELEASE_TYPE} changelog updates for version v${LATEST_VERSION} [skip ci]"
            git push origin main
          fi
          
          # Clean up: Delete both local and remote temp branches
          echo "=== Cleanup ==="
          echo "Switching to main branch..."
          git checkout main
          
          echo "Deleting local branch..."
          git branch -D $TEMP_BRANCH || echo "Failed to delete local branch: $TEMP_BRANCH"
          
          echo "Deleting remote branch..."
          git push origin --delete $TEMP_BRANCH || echo "Failed to delete remote branch: $TEMP_BRANCH"
          
          echo "=== Final Git State ==="
          git status
          git branch -a

  create-release:
    needs: generate-changelog
    if: needs.generate-changelog.outputs.version != ''
    uses: ./.github/workflows/create-github-release.yml
    with:
      version: ${{ needs.generate-changelog.outputs.version }}
      environment: ${{ inputs.environment }}
    secrets: inherit
